    var minorMagicItems=[
	["Scimitar of the Cat","Advantage to jump, spot, and listen, and move"],
	["Potion of Mint","+5 to SPIRIT Checks when dealing with NPC's"],
	["Fish Club","Stuns aquatic creatures for 1-2 rounds on a successful BODY Check"],
	["Throwing Dagger","+1 when thrown"],
	["Caribou Fur Parka","-2 to cold damage"],
	["Alabaster Jar of Chilling","Any liquid decanted into this pale, stone jar will be cooled to 52°F"],
	["Everfresh Box","Non-living organic materials placed in this box age at 1/60th the rate."],
	["Pipe of the Eternal Smoke","This silver pipe cannot be extinguished or emptied involuntarily. It can ONLY light things placed fully within its bowl."],
	["Silver Tongue Charm","Advantage on oratory or similar verbal Ability Checks."],
	["Tools of the Master _________","set of tools for a given craft (carpenter, mason, blacksmith, cooper, etc.) - no bonuses, but prevents Disadvantage."],
	["Brush of Cleanliness","A few quick strokes of this hair brush cleans anything of blood, sweat, and grime. 500gp."],
	["Lucky Coin","Gold coin brings just a little luck.. Consulting it with a quick flip before acting will sometimes make the difference between success and failure. 3/day. 540gp."],
	["Tinkerer's Hammer","Advantage to repair almost anything."],
	["Wolf Arrows","+1 arrows tipped with wolf fang arrowheads. If a wolf arrow is fired at a target that has already been hit with a wolf arrow, the arrow gets from an additional +3 to hit."],
	["Stone of Minor Spell Protection","Rough pearly stone that renders the user immune to all low level spells directed at them."],
	["Cloak of Billowing","Use an action to have the cloak billow dramatically despite the presence or absence of wind."],
	["Chime of Overloading","When used, effectively brute-forces all magical locks/wards on a single object, but breaks after use."],
	["","Silver dragon scale that glows in the moonlight. It seems almost as if the scale is trying to get back to it’s TRUE owner."],
	["","A hollowed out silver coin with a tiny encrypted message placed inside."],
	["","\"Hobo\" gold piece with the face carved into a skull, a guild symbol etched on the back, and a saying in thieves’ cant carved around the edge. Once you were targeted by a pickpocket who later returned your purse and apologized in person before fleeing in terror."],
	["","Key to a bankbox in a large bank in a large city far away, and paperwork indicating it has been paid for 100 years."],
	["","Small leather drawstring bag filled with sixteen beautiful turquoise fetishes and a note inside from someone hoping to 'meet up for another game soon'."],
	["","Curious frogmouth purse filled with many unusually shaped dice. A few small figurines of various people and creatures and worthless coins are also in the bag."],
	["","Small 5-inch gnome statue, if it gets out of view it almost seems like it’s trying to talk to you."],
	["","Board covered with runes and a silver weight tied to a string. Holding the weight over the board causes it to slowly spell the answer to any question asked. Its never the correct answer just the answer the person asking most wants to hear."],
	["","3\″ x 4\″ x 2\″ wooden box with an ink soaked sponge. Touching the sponge causes inky hand prints to appear on whatever that person has touched for the last hour. The inky prints fade in an hour and can’t be washed away. The sponge dries after one use and must be refilled with a full vial of ink before it can be used again."],
	["","Small green stone. Or red? Wasn’t it blue just now? No, it is clearly yellow…"],
	["","Shard of a mirror which shows your reflection – or rather, what you think your reflection should look like."],
	["","Spool of string, glimmering in the most astounding colours. String becomes invisible as long as music is audible."],
	["","White knight chess piece. When the player moves on the battlefield like a knight would on a chess board, it makes a sound of a horse."],
	["","Seemingly normal dagger. When it hits an enemy, you can almost hear a faint laugh. It might just be your imagination."],
	["","Musical instrument that gets louder everytime you play it."],
	["","Rubiks cube with symbols instead of colours."],
	["","Fine chain necklace fashioned from strange red metal. It retains body heat for an unusually long time."],
	["","Pocket notebook with cryptic phrases scrawled haphazardly on most of the pages."],
	["","4\″ tall wireframe model of a humanoid figure, made out of solder. The figure has an exquisitly detailed copper heart inside the dull ribcage."],
	["","Feather quill. Anything written with this appears in distinct and unknown handwriting. This unknown handwriting remains the same, regardless of who is writing with the quill."],
	["","Small pouch of glass marbles. Each marble has the abstract shape of a different animal embedded in the center of the glass."],
	["","Large decorative candle that gives off an alluring scent which, while impossible to identify, evokes a feeling of nostalgia in anyone who smells it."],
	["","Small garden trowel. The blade and handle are made of common, if not poor-quality materials, but the handle is set with a single semiprecious stone."],
	["","Sharp tooth as long as your hand, looking at it makes you uneasy."],
	["","Nail molded into the shape of a sword with pommel in the shape of a wolf’s head."],
	["","Tiny wooden horse with white hair for a mane and tail, and silver beads for eyes."],
	["","Exact replica of your own eyeball, as hard as glass."],
	["","Pretty amulet which turns out to be a highly offensive symbol to an alien people."],
	["","Document which shows whatever the observer expects to see but with a few errors (misspellings or other incongruencies)."],
	["","Flute that can either: 1 on d6 emit no audible sound (makes the nearest animal hostile), (2 on d6) an extremely high-pitched one, (3 on d6) bass strong enough to cause 1d4 damage in a d6 metre area or [4,5,6 on d6] sound like a regular flute."],
	["","Fancy dagger with an eye engraved on the hilt. When the dagger is at the very edge of one’s vision, they can swear it just blinked."],
	["","Coin pouch. It sounds, weighs, looks and feels like it’s filled with coins, but upon opening it you discover that it is empty."],
	["","Single arrow. It cannot be snapped, dulled or broken. The person who found it always manages to find it after firing it."],
	["","Tarnished brass kazoo in the shape of a fish. If blown under water it summons one normal fish of the nearest common variety. It will not summon anything monstrous but who knows what might be chasing the fish that is summoned."],
	["","Whip, when you strike anyone the whip moans loudly. Only the user can hear the moan."],
	["","Rope that ties itself into a hangmans knot every time it’s not watched."],
	["","Small statue of a gold frog with one eye and a relatively huge mouth. It knows every language and is willing to translate anything you show it but in turn for translating one word it asks to be fed one fresh (insert race) heart."],
	["","Necklace, looks like an inverted pentagram and is made of wood. If it comes in contact with blood summons a demon, over which the user has no control."],
	["","Half gold half silver coin, gold side has a sun and the silver side has a moon image on it. When used in a heads/tails way it always faces up with what the person throwing it said."],
	["","Staff made out of one long bone, ending with a skull which starts screaming when it sees a skeleton."],
	["","Crystal ball able to show you your past."],
	["","Three-lobed spinning device with almost frictionless ball bearings in the center. There are holes in the lobes and the center has a raised disk on both sides so the device can be held while it is spinning."],
	["","Small pocket watch, whenever someone holds it they swear that they’ve seen it before."],
	["","Small hourglass, the sand inside of it goes up instead of down."],
	["","Pair of dice that seem to only roll 7's when in close proximity to gold or platinum."],
	["","Coin purse that, once a day, will convert all the currency inside to whatever the local common coin is. It won’t add or subtract any, and it will leave change of what it can’t convert."],
	["","Hat with ear flaps that, once ever 1d4 hours, flap as if the hat is trying to fly away."],
	["","Pair of boots that leave tracks of a random creature, approximately the size of the wearer."],
	["","Cutlery set that makes whatever it’s user eats taste delicious, but needs to be meticulously cleaned after every use. The knife will dull, the spoon will shake and spill, and the fork will have tines break off until it is cleaned again."],
	["","Small bottle of clear liquid labeled \"Knowledge, only use in an emergency\"."],
	["","Tiny stone carving of a headless halfling."],
	["","Key made of glass."],
	["","Silver ring with a poem in Druidic on the inside."],
	["","Tiny bronze idol of a goblin carrying a knife in both hands and one clutched in his teeth."],
	["","Simple headband with a clear crystal set in the center of the brow. Can emit a red or white light on command."],
	["","Figure of a specific person with its mouth open. When you pour a liquid into it, it spits it out and then screams the name of whatever liquid was in it."],
	["","Tiny plush owlbear. It’s worn and dirty."],
	["","An blue orb that when shaken causes a light snowfall 15 feet around the player who shook it."],
	["","Egregiously decorated dagger that looks razor sharp but can’t cut through anything. It’s also twice as heavy as it should be"],
	["","Normal die that when rolled always falls on six. Everyone but the user forgets each previous roll if a new one is rolled"],
	["","Blank sheet of paper that cannot be destroyed by anything. If you write on it the words disappear and an answer is written by an invisible hand."],
	["","Mimic ring who will eat a single finger off of any person (only once per person) will tell a truth that it’s current owner wants to know."],
	["","Gold covered sapphire that opens like a locket to form a mechanical beetle."],
	["","Whistle that sounds a random note when blown into."],
	["","Small hourglass that automatically flips when the sands run to the bottom."],
	["","Teapot that is always full and piping hot, and whistles sadly if it is ever left alone."],
	["","Cooking spoon that adds a cinnamon flavor to every dish."],
	["","Lamp whose color changes subtley with the holders mood."],
	["","Keyring that is always in your pocket when you cannot find it."],
	["","Elaborate fountain pen that turns into a snake and slithers around when not being used."],
	["","Small smooth stone that seems to hum and vibrate when near a orc."],
	["Spoon of Kano","Everything you eat with this spoon tastes like chicken."],
	["Drunkard’s Hat","Fine straw or town hat, user knows the location of the nearest alcoholic beverage."],
	["Coin of Certainty","Brass coin that always lands on heads."],
	["Weapon of Mercy","Weapon that cannot strike someone below 1 hitpoint."],
	["Ring of Tracking","Simple ring, when attuned to it the user knows the location of the ring at all times."],
	["Shepherd's Staff","Can dominate a beast once per day with a MIND Check. Only works on farm animals."],
	["Wheedish Whef What","Chef's hat that gives the user Chef's cliché. User also has disadvantage on all charisma checks while wearing this hat and speaks in a strange accent."],
	["Deck of Solitary","Fine set of ornate cards in a cherrywood case. If the user attempts to play solitaire, no matter the conditions a person or creature capable of speaking at least one language will eventually show up and start trying to tell you what to play."],
	["Percussion of Movement","Percussion instrument(usually a drum. If the user has a music related Cliché, all allies in a 30' radius gain 5' of movement."],
	["Cape of Chlorophyll","Luxurious green cape, user regains 1hp per hour as long as they are in bright light."],
	["Mystic Magnet","Strong dwarven horseshoe magnet that becomes magnetic with 100lbs of force when it’s name is spoken."],
	["Lazy Boomerang","Boomerang that deals 1d6 + MIND slashing damage and will always come back after 1d20 hours."],
	["Staff of Detect Magic","Wooden staff capable of detecting magic, when activated it will detect itself and shed dim light for 10ft. Unlimited nonusefullness."],
	["Dagger of Whittling","Finely made halfling dagger that can whittle one small object once per day without the use of it’s master."],
	["Bolt of Seeking","Crossbow bolt that automatically seeks out and targets the nearest person when fired. Please note this is almost always the person who fired the crossbow."],
	["Frying Pan of Fire","A cast iron frying pan, can allow the user to cast heat metal once per day."],
	["Quartz of Procrastination","I’ll get around to writing this down. (everyone in possession of this will procrastinate)"],
	["Tome of Summon Cat","Shortly after the user attempts to read this book a cat appearing from nowhere will appear and attempt to lounge or nap on top of this tome. Repeated testing confirms the cat can walk through walls, and its origin is wherever it feels like."],
	["Conch of Gnome","Large pink and white conch shell that when spoken into will cause the speaker to hear their message back in gnome."],
	["Perfume Atraction Féline","Bottle of 4 perfume charges. When used will give the user +1 to all SPIRIT checks for an hour. Attracts all cats within a quarter mile radius."],
	["Bigger Knife","Large dagger that provides +1 to hit and +1 to SPIRIT. Dagger will grow to be slightly larger than anyone else's dagger in the room. On a failed SPIRIT check, the knife will turn into a spoon till dawn."],
	["Shovel of Jumping","Shovel (note small shovels are 1d4 damage and large shovels are 1d6 damage) This finely made shovel allows the user to jump 3x as far 2x per day."],
	["Cloak of Grace","Allows user to fall slowly once per day, billows majestically at all other times. On natural 1 rolls the cloak will get caught in something."],
	["Luggage","Can range from a tiny construct to fully grown, made out of a sentient tree this can carry up to four hundred pounds, six cubic feet or one medium sized terrified creature. Luggage is vulnerable to fire. Luggage can attempt to bite or slam an enemy at 1d8 damage. Luggage can grow from a tiny construct to full ottoman sized."],
	["Smugglers Shoes","Pair of boots that allows the user to disguise their footprints/tracks with that of any animal they’ve seen."],
	["Mouth of Minty","Cool mint tablets, 3 uses. On eating one can blow icy breath for 1d6 damage. User feels minty fresh for days afterward."],
	["Geomancer’s Glyph","Old stone carved device that allows the user to know how deep they are underground and grants Advantage in identifying different stone types. User has Disadvantage on perceptions checks made in sunlight when holding this device."],
	["Stone of Skipping","Really nice beach stone that is perfectly smooth and perfect for skipping across the water. It will always appear in your back pocket after a good toss."],
	["Homemade Peanut Brittle","Can of peanut brittle that when opened will release three fake tube snakes at random. After 4 seconds an actual flying snake emerges (Flying Snake Advantage to hit, on hit 1 damage and 3d4 poison damage) snake turns to smoke after use. Peanut brittle snakes recharge daily."],
	["The Power","Silvery glove, when worn it can turn any weapon or fist into a magic item or fist complete with thunder & lightning arcane flickers and showmanship. Said weapon or fist will retain its magicalness for 10 min, no other effects."],
	["Rock of Healing","Simple smooth rock with a glyph of healing symbol on it. As a bonus action the rock can be smacked into anybody within smacking distance. On a hit roll 1d6 and on a 3 or higher the rock heals them for 1hp, on a 2 or lower the rock inflicts 1 damage. Rock has 10 charges, all 10 charges can be used in one action, rock recharges daily."],
	["Mirror of Morality","Small vanity mirror that shows your reflection as if you has the opposite morality (often with a goatee)."],
	["Heavenly Headpiece","Fine hat, magically birds will refuse to shit on you. Hat can summon 1d20 spectral pigeons per day."],
	["Lash of Time","25ft whip can only be wielded by someone with a history cliché. Can allow for grappling hook like tricks at Disadvantage."],
	["Ring of Roundup","Carved wooden ring that attracts butterflies. Allows the wielder to control one tiny insect at a time."],
	["Pointy Prestidigitation Relic","Fine yew and copper wand. Creates a small beam of light that can be seen for miles. Can be any shape and color the user wills. Deals no damage and no other effects."],
	["Handgun","a streamlined crossbow hilt wand combination with a carved fist on the end. Fires a mage hand, that you can control, 5 shots per day.The hand cannot attack, or carry more than 10 pounds."],
	["Rake of Terror","Everyone who steps on the rake takes 1d6 damage. Rake appears to have supernatural properties in ways only the unruliest of groundskeepers is familiar with."],
	["Mirror of Positive Reinforcement","Mirror that doles out positive reinforcement and life advice. Mirrored self appears to always be smiling and wants you to know he has two thumbs."],
	["Orb of Advice","Crystal ball made mostly of Obsidian. Might just be a magic 8 ball, may or may not contain a dijin. Whispers cryptic and nonusefull advice when shook."],
	["Jar of Gaseous Gust","Sea elf made white clay jar with bands of cobalt and jet. Creates a gust of wind powerful enough to push a small or medium creature 5 ft. Requires two hands and firm concentration to operate. Using it poorly will result in flatulent noises."],
	["Violet Vexillum Mask","Mask that allows for to disguise someone once per day. However they will turn into a bright blue and purple version of who they are attempting to be disguised as."],
	["Walking Stick","Knobby arcane or druid’s staff. Will sprout legs and follow around the user when they’re not looking."],
	["Fork of Lies","Silver fork that deals 1 damage. On hit user must make a MIND Check or be compelled to lie for 1 minute."],
	["The Orange Crate","Foldable disguise that can be reduced to the size of a book. One action to unfurl and refurl, disguise is a crate of oranges and provides +1 to Checks."],
	["Rock of Uncertainty","Rock that’s impossible to know for certain what it can do."],
	["Ring of Fire","Rose gold ring, when the command word is spoken the ring heats a visible metal object to red hot. Wielder is not shielded from the effects of this. Anyone in contact with metal gets 2d8 damage. Once per day.Range of activation 100ft."],
	["Mutual Annihilation","Old rough metal bracer that’s seen intensive use and centuries. As a bonus action the user can inflict twice their level in damage in conjunction with a successful attack roll. Please note, when activated this also inflicts four times the user’s level in damage to the player character. One user per day."],
	["Witchy Wonder","Simple green nose with a bit of string. Gives the user a vile and disgusting putrid green face. It does give the user a temporary cliché in poison identification and distillation."],
	["Dayman’s Medallion","Medallion with a symbol. +1 to SPIRIT during the daytime, -1 SPIRIT and -1 MIND during the nighttime."],
	["Nightman’s Locket","Locket with the symbol of a Raven Queen. +1 to MIND during the nighttime, -1 SPIRIT and -1 MIND during the daytime."],
	["Shielding of Stoneskin","Necklace of interlocked gabbro stones. When worn it will protect the user by having them turn to stone when reduced to 0 hit points. User will pop back up to half hit points after 1d4 days or a healing spell. Roll a 1d20 on revival, on 2 or lower the necklace is destroyed."],
	["Boots of Serpents","Finely crafted snake hide boots. Once per day a small corn snake can be summoned from the boot."],
	["Dr Widdershin’s Fantastic Battletrowsers","Fantastically stylish pair of trousers. Allows the user to increase their AC by 1, does not work if user is wearing actual armor."],
	["Mystic Mouse","Small statue of a mouse. Gives the user a small craving for cheese, also gives cliché in making cheese. User can sense cheese one quarter mile."],
	["Bottomless Mug","Masterwork stone mug, all craftsdwarfship is of the highest quality. Despite being normal sized this can hold 10 gallons or 40 liters of liquid."],
	["Orb of Crack Detection","Orb that if cracked will alert the user by exploding 1 minute later for 1 fire damage."],
	["Kaleidoscope of Dreams","Expertly made brass and cobalt kaleidoscope. Adds +1 to MIND Checks made with it, on a natural roll of 5 or lower user will suffer effects of lsd(disadvantage on all ability checks for ten minutes) on a natural 20, user can see in darkness,invisible creatures and objects, detect illusions and see form of transformed creatures and objects for 1 hour."],
	["Shield of Sorrow","Decent banded iron shield with a sad drama mask engraved on the front. Once per day can allow the user to cast a command to “give up” with Advantage on a MIND Check."],
	["Babbley Fish","Mind flayer relic, a bright blue goldfish looking creature that if stuck in the ear, will allow the user to know one additional language."],
	["Dr Widdershin’s Discount Healing potions","Standard healing potion, with a god awful taste (usually rancid leeches or rooster’s feet). A MIND Check is needed to down this without it coming back up."],
	["Trampish Bag Of Dreams","Fine leather bag the looks, sounds and appears to be full of gold. Really just an empty bag that can’t hold anything except the occasionly moth."],
	["Dr Widdershin’s Invisibility Ingress Potions","Potions of invisibility that nearly work. They will instead turn you semi transparent."],
	["Pyramid Plan","Small sandal wood and glass box. The user vaguely desires whatever’s inside, +1 to hocking items in the box off on people."],
	["Robe of Randomness","Snug tweed robe. 5 times per day a random item can be pulled out of the pockets of this robe despite it not looking like it could be pulled from there. Items turn to woodsmoke in 24 hours."],
	["Pot of Pleasantness","Red and black clay pot with infernal runes. Once per day a random small plant (usually a spice) will grow from the pot."],
	["Relic of Fire Fiendishness","Squirt gun that fires a small stream of frost for 45ft. On hit deals 1 cold damage, requires water every 6 shots."],
	["Beholder’s Amulet","Small red amulet that’s covered in bumps and ridges. An eye will pop out and the user can see through it as long as it stays within 10ft of them."],
	["Tome of PseudoMagic","Tome bound in leather and several years old. Once per day it can be used to create a false publication that will back up the user’s claims. A MIND Check is needed to see through it’s bullshit."],
	["Clickity Clunker","Coconut with an engraved horse on the side. When carried it will make the sound of a horse trotting around."],
	["Sonic Soother","Rock engraved with primitive runes. When placed right side up (no one agrees on just what this is) the rock plays easy listening music."],
	["Pyromaniac’s Peppers","Small purplish red peppers, 3 charges. Allows the user to do a 1d6 fire breath weapon, tastes like burning."],
	["Rooster’s Ruin","Small bauble shaped like a rooster. Gives a rooster’s caw whenever the local equivalent of dawn happens."],
	["Magnifier of Mayhem","Fine bronze magnifying glass. Can shoot a beam of radiant energy 30ft, deals 1 radiant damage."],
	["Laughing Lock","Lock with an engraved picture of a laughing face on it. Only opens to knock, a natural 20, or if someone tells a joke while lockpicking or opening the key."],
	["Menace of Marbles","A marbles game bag that provides 1000 marbles that can be summoned (treat as ball bearings) MIND Check to avoid them. 1000 marbles creates four 5x5 ft squares. Marbles turn to dust in 24 hours and bag recharges daily."],
	["Pipe of Peculiar","Fine wooden pipe creates a 20' radius puff of smoke once per day. MIND Check to see through. Smoke is fine woody and mildly addictive."],
	["Scarlet Salmon","Wand that looks suspiciously like a small fishing rod. It gives the user the ability to create one red flying fish illusion, range 60ft."],
	["Dyson of Dead Sun","A crystal ball that contains different scenery every time it’s used. When shook, a large thaumaturgical or nuclear explosion takes place and the scenery changes inside the sphere."],
	["Knuckles of Knock","Pair of sturdy ironwood knuckles. When activated they grow into a portable ram (Advantage to breaking down doors). It’s an action to convert these into a ram and back again."],
	["Spellslinger’s Staff","Walnut and nickel adorned staff that makes unnecessary clicking noise when handled. Advantage to initiative when in a fight, Disadvantage to stealth Checks."],
	["Boogie Boots","Pair of high heeled leather and iron boots, provide Advantage to mosey, strutting and kicking Checks. Killer on the feet though, -1hp for every hour wearing the boots."],
	["Champions Chessboard","Fine elven made chess board made with white quartz, basalt, and red cedar. User must win a chess game with this board to use it. Chess pieces will slaughter each other and mend after every game. Chesspieces will obey one command from you out of game for thirty minutes (treat entire team as a tiny construct.)"],
	["Sir Stuffed","Small stuffed animal that carries a wooden sword and a small helmet. Can be used to keep guard while people sleep, and will wake the owner when danger arrives. In true life or death situations it will defend the user. Sir Stuffed has 3hp, Advantage to Attack Rolls and on hit deals 1 damage."],
	["Hunter Fishhook","Fishhook that seeks, kills and attempts to return a fish once per day. Fishhook comes back in ten minutes with or without it’s prize. Commonly returns fish the size of goldfish, or kills larger fish and is unable to bring them back."],
	["Cursed Crystal Cantos","Relic that turns any semi organic material around it into candy. Produces ½ a pound per day and will use anything around it as ingredients."],
	["Weapon of Eternal Forge","Mystical glowing shortsword of unusual property. Functions as a -1 sword for all attacks and damage rolls, breaks entirely on natural 1s. Mends itself in one day though, sword appears to be attempting to reforge itself constantly through magic due to the creator being convinced the magic will work itself out eventually."],
	["Belt of BiteBack","Fine leather belt that can transform with a crack into a 15' magic whip. On every miss, hits the user in the face for 1 damage. Belt requires an action to crack back and forth between belt and whip."],
	["Bow of Base","Older underdark orange bow with character. It strums a steady base line, Disadvantage to all stealth rolls, Advantage to all unnecessary trickshots."],
	["Creature’s Crossbow","Crossbow made of unfamiliar wood full of notches and twists. Appears to have been made for some kind of unknown creature that’s designed differently from normal humanoids. Functions as a light crossbow, once per day can be used to inflict 1d6 of a random damage type onto a successfully fired shot that the user also takes. Requires a MIND Check to understand how to activate this."],
	["Ax of Armistice","Well made steel greataxe made by tieflings. Advantage to intimidation, Advantage to hit, if an enemy is killed with this axe all extra damage is carried over to another enemy within 10ft. Make SPIRIT Check, if failed the user will attempt peace first until they are hit for any damage or are persuaded to attempt violence, MIND Check."],
	["Amulet of Alms","Amulet made out of white gold and adorned with an arrow. Gives the user Advantage to any check, that they can use on themselves or anyone within 30ft as a bonus action. Amulet can also be used to point to the nearest hallowed ground or a place of worship once per day."],
	["Staff of Serendipity","Three times per day the staff can use it’s user’s reaction to increase their armor class by 3. Daily make a MIND Check, on fail the user believes the Staff can allow them to fly until they're talked out of it, SPIRIT Check or proven wrong the hard way."],
	["Ace of Spades","Ace of spades from a standard card deck. No matter where you store it on your body, you will always be able to find it in your right sleeve afterwards."],
	["Arrow of Euarere","Silver arrow, suspended on a string. It always points to the person holding the string."],
	["Amulet of Extra Amulet Slot","Amulet allows you to gain the benefit from two magical amulets rather than one. It cannot be further enchanted."],
	["Anti-Matches","Box of matches. Striking one will make it begin to drip water from the tip while the match shrivels away. The amount of water a match releases is about enough to fill a tablespoon."],
	["Artist's Bludgeon","Inanimate objects hit with this bludgeon will receive no damage; they will however change color."],
	["Attentive Guardsman's Pike","Ornate and deadly-looking ceremonial pikes with fluttering banners that can be unfurled for parade use. They only weigh one pound, and inflict only a single point of damage, being almost entirely for show. They also have the property of remaining in place when set able to support 20 lbs."],
	["Attentive Guardsman's Tabard","A dozen of these tabards were fashioned for palace guardsmen, 250 miles from the nearest enemy. The bearer is placed under a glamour that causes him to appear alert and awake, even if his eyes are closed and he is snoring lightly."],
	["Axe of Big Numbers","This axe shouts \"Big numbers baby, come on!\" whenever it is swung, but always deals 1 damage or less."],
	["Axe of Empathy","Every time you hit something with this +5 greataxe, you get dealt an equal amount of damage. Both you and the thing you hit are then healed the amount of damage dealt by the axe, even if either are dead. The Axe hopes you have learned your lesson."],
	["Axe of Pain","Axe is always moaning and groaning with pain."],
	["Baby Oil","An aphrodisiac made from the finest mashed babies. Strangely unpopular in the upper planes, the judgmental prudes."],
	["Bag of Faerie Gold","Sack appears to be full of gold coins and jewels. When one attempts to spend them, however, the glamour on them soon vanishes, revealing them to be nothing but leaves and pebbles. Obviously, most shopkeepers will not be happy about this, and no amount of \"we didn't know, I swear!\" will change their mind."],
	["Bag of Trading","You can take one thing out of the bag for each object you put in the bag. However, you have no control over what you get, and there are no trade-backs. Past research seems to imply there's some sort of correlation to what gets you what, but it's extremely convoluted and far from understood."],
	["Bag of Trick","Ordinary bag, appears empty, once a week the user can reach in and produce a rat each time it is used."],
	["Bag of Unholding","Quite a large backpack but even the smallest item doesn't fit."],
	["Bagpipe of Stealth","Grants the user invisibility as long as it is being played."],
	["Ball of Eyes","A snow-globe filled with miniature eyeballs. When shaken, it grants the user a blurry, jittery vision of some remote event."],
	["Belt of Pants","Belt creates illusory pants on the wearer. The wearer can suppress the illusion at will"],
	["Belt of Tightening","Every time you put this belt on, all of your clothes permanently shrink a fraction of a millimeter. The effect compounds."],
	["Belt of Unbathed Breath","When worn around the waist, allows the user to breathe underwater. Does not function when wet."],
	["Boogie Skeleton","This pile of bones is small, such as one that might be obtained from a bird or a toad, though it can look as though it came from any creature. When a song is sung or played in the vicinity of the skeleton, it begins to dance appropriately. As soon as the music stops, it collapses into the pile of bones again.."],
	["Book of Canon","A book that automatically transforms into a copy of the sacred text of any religion, translated into the language the user is most familiar with."],
	["Book of Confusion","The letters in this book always appear to be upside down, even if viewed from different directions at the same time. The book is a bad novel about zombies."],
	["Book of Curses","When opened, the book verbally berates and insults anyone in the immediate vicinity. Once closed the book continues shouting (although it is muffled) until placed inside a bag or similar for 1d4+1 minutes and ignored. Replying to the book in any other way causes the insults to get louder and more childish the more time you spend replying to it."],
	["Book of Exalted Deeds","Contains a listing of some of the finest houses ever sold and the specifics of the titles to the properties."],
	["Boots of Levitation","Boots levitate a few inches off the ground when not worn."],
	["Boots of Stylishness","Knee high black boots that are always clean and shiny. They never take in water, thus feet are always dry."],
	["Boots of Walking","The wearer of the boots cannot run, nor can they take a double move action, and has Disadvantage to tumble Checks. \"These boots are made for walkin', and that's just what they'll do.\""],
	["Bottle of Air","It's a bottle. Full of air. Congratulations."],
	["Bottomless Beer Mug","Any liquid poured into this mug treats the bottom as incorporeal, but solid objects don't."],
	["Bowl of Comfortable Warmth","Any liquid in the bowl will feel comfortably warm, so icy cold water will feel like it's a bit over room temperature. Do note, however, that it's still icy cold water, it just feels warmer."],
	["Box of Mild Interest","If this box is held in two hands and shaken, using an action, it may generate an effect. Roll 1d20. 1: Paralyze the user,2: Paralyze the closest non-using creature,3: Dancing Lights as desired by the holder,4: Sleep on the holder,5: Sleep on a creature of the holder’s choice,6: Holder takes 1 force damage, no save,7-20: No effect"],
	["Breastplate of Secret Detection","If the wearer of this breastplate gains a piece of information that is somehow connected to the concealment of a hidden conspiracy or plot, a live and still wet red herring forms on the inside of the armor."],
	["Bullying Gloves","At random intervals, these gloves instil the wearer with a near-irresistible urge to hit themselves."],
	["Bunyan’s Belt","When worn, causes an enormous, bushy black beard to appear on the wearer’s face."],
	["Cape of Resistance","When this item is placed on any living thing it somehow manages to fall off, untie itself, slip past the owner’s neck entirely, or otherwise avoid being worn."],
	["Case of the Litigator","Translates any document placed in the case into legal jargon; non-reversible. Does not confer the ability to understand legal jargon."],
	["Cat of Schrodinger","When this cat is not being observed in any way it is both dead and alive. When something observes it, it suddenly becomes either dead or alive with a 50% chance of either."],
	["Chair of Steadiness","This chair can be moved but cannot be tipped over except by BODY Check with Disadvantage."],
	["Charles","This small, unremarkable figurine of a gnome refuses to be called anything but Charles. No other name will leave the lips of the speaker. It has no other powers."],
	["Chime of Opening","Commonly affixed to or near doors, when pressed it emits a sound on the interior of the owner’s home to let them know guests have arrived."],
	["Chime of Opening","When struck against a solid surface, this chime emits a loud click, and opens along its length, to reveal a tiny compartment adequate to conceal a single 'smoke' worth of pipeweed or a blowgun needle. When the compartment is closed, it is seamless and can be detected only with a MIND Check with Disadvantage. If hit with an instrument such as a small mallet, it chimes."],
	["Cloak of Billowing","This black and silver cloak will always billow dramatically behind the wearer, it has no other effects."],
	["Cloak of Displacement","Appears to be a normal cloak, but when worn by a character its magical properties distort and warp reality. When any attack is made against the wearer the cloak has a 20% chance of falling off, no matter how it is secured."],
	["Compacting hammer","The force imparted by it is multiplied, but is spread around the surface of a struck object facing inward."],
	["Cymbal of Symbols","This musical instrument enables the user to comprehend dead languages, but only while they are deafened by noise."],
	["Dagger of Told Secrets","Simple-looking dagger. If used to backstab someone to death, it will whisper your most significant secret to that person."],
	["Dagger of Untold Secrets","Simple looking dagger. If used to backstab someone to death, it will whisper the most significant secret of that person to you."],
	["Decanter of Endless Sorrow","Pewter flask that produces limitless alcohol when held to their lips by someone who is troubled. It gets them drunk but they never feel any better."],
	["Diadem of Brothaurity","When wearing this headpiece, you are as elegant and well-spoken as a famous diplomat or regent, but you can't stop calling everyone bro."],
	["Enchanted Book of Collected Stories","Opening this will cause miniature creatures/people to pour out and perform a chapter from the book much like a theater."],
	["Fade to Black Belt","The wearer of this belt will be unable to remember any sexual encounter begun while they were wearing the belt."],
	["Focusing Ring","The digit on which this ring is worn can be viewed in extremely high definition from a great distance."],
	["Gloves of Tinkering","Wearing the gloves will make you able to almost repair any broken item. However, you will always end up with pieces from the item that don't seem to fit anywhere."],
	["Greater Staff of Random Summoning","Summons a random creature at a random place. You could be summoning a giant Ogre on the other side of the globe for all you know."],
	["Hoarder's Wand","Does nothing but for some reason you think it might be important later in your quest."],
	["Hood of Offensive Facades","This hood will change your identity in the eyes of others to the appearance of the person they most personally dislike."],
	["Hood Of Worrisome Facades","This hood will change your identity in the eyes of others, however the identity used will be random."],
	["Intransigent Rod","When the button on this artifact is pressed in, the holder's opinions solidify and they become impossible to convince."],
	["Lunchbox of Delicious Unfulfillment","This lunchbox will hold whatever food you desire. However you will never get full and the food will deliver no nourishment."],
	["Mattress of Poverty","No matter how you fluff this gorgeous, thick, mattress, you will always sleep on the thin part of it."],
	["Mug O' Dissatisfaction","Mug that always produces a steaming hot cup of coffee or tea when tapped on the bottom. It conjures the opposite of what the tapper prefers, so if you like tea you get coffee and vice versa. Handing the full mug to another person will make the drink in it transform to the opposite of that persons preferences."],
	["Murder Dagger","All damage it would deal is instead replaced by the target being harassed by crows for that many hours."],
	["Needle Of Learned Compromise","This needle will create beautiful tattoos of any design, however they hurt a tiny bit more. When used to sew it is entirely normal."],
	["Ring of First Impression","Wearing the ring will make you able to perform a perfect handshake with the hand wearing it."],
	["Sack of Hive Eggs","Crushing one of the numerous tiny eggs will cause the thoughts of everybody in the proximity to merge. Everybody can hear what you think and you can hear everybody."],
	["Shield of Protecting","This is metal shield that absorbs all impacts. However, every time it is hit it moans loudly for more. It'll start begging if it isn't hit within a certain amount of time."],
	["Shoes of the Restless Traveler","These shoes allow their user to run for miles without feeling fatigue, but if they try to do anything else with it (walk, sit down, jump), they will instantly trip"],
	["Vorpal Grindstone","It can \"sharpen\" any object to become vorpal. Any object."],
	["Wineskin of the Eternal Primary","This wineskin never runs out of water, but even the tiniest sip makes you have to go, like, super bad. Right now."],
	["Whisper Wind","Small piece of paper that turns into a small breeze that carries your message to your target when whispered to. Unless said target is really attentive they'll likely miss what the message was."],
	["Cloak of the Racoon","Once per day, the wearer can cast *invisibility* on themselves. In addition to the normal conditions, the spell ends if the wearer moves from their current position. (Our sorcerer uses this all the time to get out of trouble)"],
	["Goodberry Wine","The bottle holds up to 10 sips of goodberry wine. As an action, a player can drink anywhere from 1 to 10 sips, gaining 1 HP for each. The wine also sustains a creature for a day as if they had had food and water, as per the *goodberry* spell."],
	["Beast Whistle","Once per day you can use an action to blow the whistle, magically teleporting the creature to your side."],
	["Boots of the Cat","While worn, you have resistance to falling damage, and are never knocked prone from a fall as long as you're not incapacitated."],
	["Deathwatch Eyes","While worn, you can tell by a glance if a creature you can see within 30 feet is dead, dying, stable, alive, undead, or none of these (such as constructs)."],
	["Heavyload Belt","While worn, your carrying capacity is doubled."],
	["Bejeweled Weapon","This weapon strikes as magic and silver."],
	["Seraphim Necklace","While worn, when you drop to 0 hit points (but are not killed outright), instead of dropping unconscious, you immediately heal 2d8+4 hit points, and the necklace shatters."],
	["Tomahawk","Magical axe when thrown will always immediately return to its owners hand after a hit or miss."],
	["Gulthias Apple Seeds","When consumed eater rolls a d20 on a 1 take 1d4 Damage otherwise restore 1HP."],
	["The \"Bow of Elemental Fury","Bow is carved of fine wood, with motifs for fire, frost, and lightning etched all over it.When you make an attack with this bow you can choose to have it deal its normal damage type, or have it deal fire, cold, or lightning damage instead."],
	["Sharnock Blades","Enchanted to never rust, never break, and always look/be clean, and furthermore extends the cleanliness to all near it. Any thing and anyone within 10 feet of a Sharnock blade will find itself completely clean within minutes, even worn clothes and hidden creatures. Will nullify the Stench ability of Troglodytes."],
	["Earring of Honeyed Words","Once per day, this earring can whisper words of advice or encouragement to the user, which can be used to add Advantage to a SPIRIT Check."],
	["Dashers Boots","3 times per day, the wearer of these leather boots can run like the wind. For a single round, the wearer's speed and jump distance is doubled and they can use dash as a bonus action. Once used, the boots can not be used another time for 1 minute."],
	["Chlorophyll Ring","Emerald gem set within an adamantine ring. One charge that restores each dawn as long as the sun is visible. Use one charge to cure 1d4 hp on yourself as a bonus action."],
	["Shield of the Protector","normal +2 to AC but allows a bonus action to roll an attack that does 1d4 bludgeoning damage. Also twice per short rest can give Disadvantage to an enemy attacking another party member within range."],
	["Hammer of Brawling","Advantage when breaking down doors, on a 20 does 1d6 extra damage and knocks target back 10 feet."],
	["Ring of Stoneform","Turns wearer into stone, granting them stoneskin. Must be removed by someone else."],
	["Ring of Quiet Contemplation","You gain +4 bonus to MIND but are under the effect of the silence spell while wearing this cursed ring."],
	["Slippies of Haste","Advantage on Initiative"],
	["Fletcher's Mitt","Gives you +1 AC against ranged, non-magical attacks. If you successfully avoid a ranged, non-magical attack, then you are able to grab the projectile out of the air."],
	["Amulet of Emergency","Once per day, whenever a creature within 60 feet of you falls unconscious, you may heal them of 1d4."],
	["Lens of Straight Creepin'","A monocle that allows the user to once a day see the footprints of a specific person or creature that has been within the area."],
	["Spool of Endless Rope","A spool of endless rope contains an unlimited amount of the finest silk rope, yet the whole spool weighs only a single pound and comes with a belt loop so that it can be hung conveniently at an adventurer’s side.Any portion of rope cut away from the spool disappears instantly.The rope from a spool of endless rope can be spliced or knotted together with another rope (including a rope from a second spool of endless rope), but the rope can’t be wound back into the spool while so attached."],
	["Key of Locking","Overly ornate key that can shift to match any lock and can only lock it."],
	["Stick of Shininess","Twig grants the wielder Light, also makes whatever it touches emit light for (1d6 x 10) minutes"],
	["Marvelous Mixer","Large wooden spoon with a small red crystal affixed to the end of the handle will autonomously stir the contents of any container it is placed within, does not function when it is not placed upright in a container."],
	["Hat of Hairiness","When you don this hat, it causes your hair to grow profusely until you have a fantastic and unruly mane. Simultaneously, you grow quite attached to the look and unwilling to change it without the benefit of a remove curse."],
	["Rebuking Shield","The shield is finely crafted from a combination of hardwood and hardened steel. While you wield this shield you gain +1 AC while wielding it. If a creature hits you with an attack, you may you your reaction to shove back, dealing 1d8 damage to the offender. This can only be used once per short rest."],
	["Bagpipes of Distraction","The bagpipes is beautifully made from a rich mahogany wood, artfully carved and well balanced. As an action you may play a tune to inflict Disadvantage to a target that can hear you play as the music played distracts them."],
	["Gourd of Teleportation"," When this large gourd is thrown and breaks the thrower is instantly teleported to that location. Single use."],
	["Wooden Spoon","Carved with rune for \"food\". When tapped on an inert organic or semi-organic material (wood, dirt) it turns that stuff into edible foodstuffs, although it will be mushy and unpalatable."],
	["Amulet of Hope","Shines as bright as a candle, but only when there are no other light sources. Light points back towards dungeon entrance, vaguely. Hums reassuringly when clutched, and warms your hand."],
	["Orphan's Top","Cannot be spun if there are any invisible undead nearby."],
	["Ring of the Adventurous Limb","If worn on a hand, the entire arm will vanish. It will return after 24 hours have elapsed. Roll a d10: 1 - tattoo on arm, 2 - arm injured, 3 - gained a ring, probably a wedding ring, 4 - ring missing, 5-10 - nothing special. It will have a similar effect on legs."],
	["Dust of De-Appearance","Can make things invisible, but wears off if the object moves, is moved, or even wiggles a bit. Best used on inanimate objects or people who can hold really, really, still."],
	["Paired Scrolls","Whatever is written on one appears on the other. Give players a 3\"x5\" card to write on, to limit how much they can write."],
	["Book of Epic Boredom","When reading, Check vs MIND or sleep."],
	["Black Cigarette","When smoked, it creates a huge cloud of smoke and allows the smoker to see through smoke and fog. Can be smoked for 5 minutes (or 5 one-minute segments)."],
	["Colorthief's Brush","If you hit something with this paintbrush, you steal all the color from it, but can later paint with those same brilliant colors (stored in the brush, controlled by imagination). If a book is smacked, it will steal the words. The book can then be reconstructed, but it takes a few days of writing for it to be recovered."],
	["Sleeping Draught","Sleep TWICE AS HARD for four hours. You get a full night's rest, but cannot be woken up. Unwilling targets get a MIND Check."],
	["Love Potion"," "],
	["Exploserous Carnelian","When activated, begins to glow hotter and hotter. Explodes like a stick of dynamite after 1d2+2 rounds."],
	["Mighty Acorn","When thrown on the ground, immediately grows into a 20' oak."],
	["Mechanical Torchbearer","Follows the associated amulet. Can hold 6 torches, and relight a new one as the old one burns out.Looks like a mechanical spider, 5' in diameter."],
	["Penguin tokens (1d6)","Summons an 80 lb emperor penguin. On land, cannot do anything except waddle to where you direct. In water, can attack as a 1 HD creature. Is destroyed/killed if it takes any damage. Reverts to a small, 1\" wooden token after 1 minute."],
	["Saint's Bones","About the size of a cigar box. Contains mandible & some carpals. Will rattle ominously when a lie is uttered nearby."],
	["Amber Comb","Any lightning attack within 10' is diverted to the comb instead. If the comb takes 6 or more damage (it is not immune to lightning), it shatters."],
	["Chewed Bone","When chewed, it fills the air with the smell of delicious fresh meat. This is strong enough to mask other odors."],
	["Bottle of Light","When swung overhead, absorbs ambient light. Later, the bottle can be unstoppered to allow the light back out again. Can hold up to 5 rounds of light. Special properties of light are preserved: moonlight can induce lycanthropy, for example."],
	["Silver Silk Handkerchief","3' on a side.On command, it becomes as hard as thick steel. A command reverts."],
	["Silver silk rope","Rope 25'.On command, it becomes as hard as thick steel. A command reverts."],
	["Vial of Nightshade","When drunk, it puts the body into a deep coma and ejects the spirit.You can now roam around, incorporeal, until you return to your body.There is a 1-in-6 chance each hour that some mishap befalls you (body possessed by outsider, soul lost forever, etc).Coma lasts for 1d3 days."],
	["Grinning Amulet","Anyone who laughs--even a snicker--near this amulet must make a SPIRIT Check or laugh uncontrollably for the next minute. Careful, it's contagious--if a player laughs during this, so does their character."],
	["Trollwax","Tacky and unpalatable. Anything that tastes it must succeed on a SPIRIT Check, or be so disgusted that it cannot taste it again. (Takes a week to fully leave the tongue.)"],
	["Cheater's Coin","When flipped, it will give whatever result the owner wishes. This is not limited to heads/tails--it can also give results of king, dragon, treasury, pilgrims, etc."],
	["Boots of Independence","When you remove these boots and fail to restrain them (put them in a pack, etc) they will walk back the way they came, all the way back to where you first put them on, with more-or-less the same cadence and sounds. If you walked in a loop somewhere along the line, the boots will get stuck in the loop and repeat."],
	["Tiny Tree","Produces three fat apples every day (enough to feed 1 person).Must be watered with 1 cup of blood each day, or it will die. If dead, can be revived with water. Probably found dead/in a chest."],
	["Skeleton Gourd","This gourd has a peephole. Anyone holding the gourd up to their face and looking into the peephole will be paralyzed while their brain is filled with visions of dancing skeletons."],
	["Ring of Petrification","Putting this ring on will turn a person to stone, except for the ring. Someone else can remove the ring, and thereby return them to flesh."],
	["Party Book","This book creates audible illusions imitating a party. The state of the party depends on the page the book is opened to. If the book is turned to page 1, you'll hear a couple people setting up silverware. Middle of the book, raucous carousing. Near the end, mostly snores and a few people taking shots."],
	["Quiet Bell","This 2\" tall silver bell prevents all sound within 1'."],
	["Palette of All Colors","Contains 7 mundane palettes (ROYGBIV) and 1 color that is invisible to humans. If the invisible color is painted on a wall, it allows people to see through it. Can paint up to a 3' diameter spot, or 10 3\" peepholes. Penetrates no more than 6\". Getting it on someone's face blinds them."],
	["Slimming Cone","When touched to a creature, it instantly and harmlessly sucks out all the excess fat from them, ejecting it onto the floor in a big mass."],
	["Grass Whistle","When blown, roll for a random encounter. If the location has no encounter table (some cities, maybe), the PCs will meet someone interesting who wants something."],
	["Naiad-hair Ring","50% cursed. When worn, PC treats all water as if it had the consistency of a gas. (Don't fall off a boat.) Water is still unbreathable."],
	["Ring of Swimming","Wearer treats air as if it had the consistency of water. You can \"fly\" by swimming through the air, but the air is too thick to breath.Other water penalties also apply."],
	["Belt of Cat Imprisonment","When laid on the ground, felines are compelled to sit in the center of it, as charm."],
	["Endless Boots","\"Cannot stop walking\",\"Will never tire from walking\",\"Cannot run\",\"Walk walk walk\"."],
	["Spike of Woodland Suicides","Sort of like a hunter's trap. When left in the woods, wild animals will come and impale themselves on it. A verdant forest yield 1d10 rations worth per day, but must be moved daily. Fey will fucking hate you, though."],
	["Salt Block","Any food you carry will never spoil.Doesn't have to be on your person. Applies to a captain and his ship's cargo, for example."],
	["Log of Alarum","This 300 lb log protects those who sleep with their heads against it.If they would be attacked in their sleep, the log has a 90% chance of waking them up (by making bird song)."],
	["Everice","Never melts."],
	["Chest of the Mundane","Anything placed inside it is covered with an illusion that makes it look worthless and boring. Currently holding 3 peridots worth 10gp each."],
	["Fox-in-a-Bag","Sleeps all the time. As soon as it touches the ground, it will run around like crazy. MIND 15, AC as plate because of high dexterity + foxy nature. If you pick it up (good luck) it will fall back asleep."],
	["Feather of Bravado","When placed in a hat, it points in the direction of the nearest deadly foe capable of killing the PCs. When placed in the bottom of one's shoe, allows them to run slightly faster."],
	["Gossip Cookies","Each one contains either a random rumor from the most relevant rumor table or \"You will be killed by [random monster from most relevant random encounter table]\". 50% chance of each."],
	["","Small silver figurine that, when given away, will return to your pocket after 1d6 minutes. The only way to permanently get rid of it is for the recipient to similarly give it away before the 1d6 minutes expire. (Alternatively, the original owner could die.) Yes, this is great for scamming people."],
	["","Rock that, when thrown, always hits its target. Always. Cannot do anything that you couldn't conceivably do with a really lucky throw."],
	["","Saddle that turns any animal into a horse when it is strapped on. The horse cannot remove the saddle on its own. Currently owned by a bounty hunter who is fond of riding his bounties back to town."],
	["","Key that can unlock any door, but cannot be removed from the mechanism until the door is relocked."],
	["","Mug that points the way to the nearest tavern when it is balanced on its edge."],
	["","Egg cup that can hatch any egg that is placed atop it."],
	["","Ring that gives the wearer a magnificent mustache/beard, depending on which finger it is worn on. The left ring finger, for example, always yields a Van Dyke."],
	["","Ring that makes your eyeball pop out. This is not a problem, and you can continue to see through the eye just fine, like a spy-eye. Reversible if the ring is removed."],
	["","Ring that makes you invisible, but not your equipment or clothing."],
	["","Umbrella that allows you float downwards at 60'/round when open, negating fall damage."],
	["Chicken Arrows","(1d6). On a hit, target must succeed MIND Check (first arrow only). If sat upon like an egg, quickly turns into an adult chicken. Fletched with white feathers."],
	["Bag of Infinite Manure","Useful for campfires."],
	["Wand of Necromantic Cooking","Can enchant a corpse or cut of meat to cut, prepare, marinate, and cook itself. A slaughtered pig will seek out gravy to roll around in. Sausages will jump into the saucepan, and then seek out your plate when cooked."],
	["Omnidress","Can turn into any type of dress (can even imitate leather armor, but not metal)."],
	["Indelible Pen","Can write on anything. Writing is permanent. Works 1d6 times."],
	["","Ring that makes the wearer appear to be dead and rotten."],
	["Scones","(1d6). When broken in half, it erupts into 1d100 scones (10 scones = food for a day). Alternatively, it can be eaten to restore 1d6 HP."],
	["Wooden Hand","1/day, can turn into a living-but-disembodied hand for 1 hour. Will obey your commands for the duration. BODY 1, can climb most walls. MIND 2, can see normally, but cannot speak."],
	["Locket","Woman's face inside the amulet always looks towards (insert town name here)."],
	["Box of Paired Snails","When one snail dies, so does its mate. Normally used to send very crude, binary messages. There are 1d6 pairs of snails. Feed them leaves."],
	["Hungry Coin","Cursed. Will attempt to eat other coins that it comes into contact with. Eats 100 coins an hour."],
	["Armor of Glamour","Looks like a fancy dinner suit. Is actually a suit of plate mail."],
	["Ring of Good Omen","The first time you fail a Check against a curse or other magic, the ring breaks and you instead succeed your Check."],
	["Prayer of the Seal","When this sheet of paper is attached to a door or portal, it becomes locked (until the paper is removed or destroyed.)"],
	["Boots of the Aristocrat","When you click them together, your clothes become clean, your skin becomes perfumed, and your hair is styled."],
	["Cursed Matches","(1d6). When lit, the match does not ignite. Instead, whatever the PC is looking at catches fire. (Tiny match-sized fire. Does no damage unless allowed to progress.)"],
	["Preservative Jar","Anything placed in this jar enters stasis. Cannot hold anything bigger than a toad. Currently holds a toad."],
	["Library Box","When a non-magical book is placed inside it, another of the same type will be found there the next day."],
	["Monocle of Entropy","If you stare at something long enough, it will fall over. 1 round for a candlestick, 1 minute for a sleeping cow, 1 hour for a small tree, 1 day for a cottage or large tree, 1 week for a castle. Must be within 100'."],
	["Stick of the Titan","Hits for 2d8, then breaks."],
	["Singing Frog","Knows 1d6 songs. Good for a free round of drinks in pretty much any bar you walk in to, with only a 20% chance that someone will try to steal it from you at the end of the night."],
	["Perpetual Motion Machine","Utterly unremarkable in a world filled with magic, but still cool."],
	["Seed of Moon Ice","If dropped in a body of water, will \"freeze\" an area up to 20' diameter. If swallowed, you die. If touched, BODY Check or die. Leaves awesomely frozen corpses that are not cold to the touch and never thaw."],
	["Small Broom","When activated, will attempt to clean the dirtiest thing nearby."],
	["Blindfold of the Spirits","When worn, you can attack incorporeal things as if they weren't. Also, you're blind."],
	["Night's Black Windchimes","25% chance of alerting you when you would be attacked during the night. If one of the 1d6+1 chimes is broken in half, a refreshing (but also quite cold) breeze blows through the area."],
	["Dust of Vermicide","When thrown, does 1 damage to everything in a 5' diameter area. Alternatively, does 2d6 damage against a swarm."],
	["Sovereign Glue.",""],
	["Universal Solvent.",""],
	["Goblin cloak","Invisible while in shadowy areas, but stinks like a mound of goblin shit."],
	["Miser's Flute","When played, all unsecured coins in 20' will leap up and roll after you. They will follow you as long as you play, and as fast as normal running speed. Uphill is fine, stairs are not."],
	["Donkey Legs","These wooden donkey legs can be attached to anything (but are not strong enough to carry literally anything). Once attached, the thing will follow you around like a loyal donkey. For example, you can attach them to a heavy statue and then have it walk itself out of the dungeon. Donkey legs are as strong as two donkeys!"],
	["Giant's Ochre","Anything painted with this pigment will double in size. Washes off easily with water or sweat. (If you paint yourself, it'll wash off after 1d6 rounds of sweaty combat)."],
	["Mask of the Jester","Anyone seeing it for the first time must MIND Check or be compelled to attack the wearer."],
	["Eye of Zin","If this jewel is pressed into the forehead, the wearer's eyes turn jet black, they gain darkvision, and they are blinded by even small amounts of light (a nearby torch will blind them, for example)."],
	["Metal Eye Mask","Wearing this mask obscures you normal vision, but allows you to see from above, sort of like a flying hawk's view. At sea level, you can see an area 200' in diameter, centered on the mask."],
	["Pink Bead","When smashed on the ground, immediately turns into a huge mountain of fluffy bubbles, similar in consistency to a mass of fused marshmallows. Can cushion a fall or block a hallway or something. 10' in diameter, can be cut through with 6 slashing attacks, lasts 1d6 minutes."],
	["","Animate rope with the personality of a loyal dog. 50'. Must be taught knots the way a dog must be taught tricks."],
	["MIRROR OF YOUR BEST SIDE","Magic mirror that makes you look 5-10 years younger, 10-20 kg lighter, no bags under your eyes, no patches on your skin"],
	["FLINT OF SURETY","A magical flint that will alight any tinder to form a fire, in almost any circumstance. Sure, why not underwater?"],
	["SOCKS OF LIGHT FOOTNESS","Socks to make walking over annoying stones and other terrain a little easier. Makes terrain half penalty"],
	["SHIRT OF WARMING","In cold climates this shirt might act as half a warm blanket. Keeps warm from cold exhaustion, but not against Cold magic etc. (is a wizard feeling a chill in his tower)"],
	["DUAL BURNING CANDLE","You've heard the term \"burning the candle from both ends\"? Meaning you stayed awake all night. The Dual Burning Candle allows you to stay awake all night performing intellectual activities, without suffering exhaustion. One night only. Not allowed for physical activity."],
	["PEBBLE OF PURE NORTH","Pebble that will always point pure north"],
	["GEMSTONE OF REMEMBERING","GGemstone that can be asked a simple YES/NO answer about where/when characters have been. D6 charges until gone"],
	["SAUCEPAN OF EVERFILL","Pot that, once filled, keeps filling up with foods/drinks until lidded"],
	["SHAMING STICK","A wand that makes an NPC feel bad. Loses Advantage. DM ideas to Role Play disadvantage"],
	["COOKSBLADE","Can use blade to portion minimal food to feed up to 20 people"],
	["CANDLE OF FLICKER LIGHT","On a word, this candle will light up a 10 foot radius, enough to read."],
	["BLADE OF NEVER RUST/ANTI-CORROSION","Sword can never rust. Won't lose edge. Rust monster etc."]
	["Travel Cloak","Lightweight gray-green cloak protects the wearer against cold. Also, the cloak sheds precipitation. Three times per day, the wearer can reach into one of the pockets of the cloak and pull out trail rations. From another pocket, the wearer may withdraw a stoppered 1-quart metal flask that produces either pure cool water or sugared hot tea. The flask produces up to two gallons of liquid per day. The flask only refills if placed back in the pocket of the cloak; if separated from the cloak or wearer, it has no magical properties. Finally, when the wearer utters a command word, the travel cloak expands once per day to the size of a one-person tent."],
	["Dwarven Mug Of Ale","Any nonmagical liquid you put into it turned into a strong dwarven ale, but if poured out, changed back to the liquid it had been, so it was only useful for getting drunk."],
	["Potion of Red Dragon Control"],
	["Battle Axe +3"],
	["Phylactery of Long Years"],
	["Buckler +1"],
	["Ring of Shooting Stars"],
	["Pipes of the Sewers"],
	["Ring of Blinking"],
	["Shield +3"],
	["Dagger of Throwing +3"],
	["Wand of Fireballs"],
	["Plate Armor, Full +1"],
	["Ring of Chameleon Power"],
	["Potion of Heroism"],
	["Potion of Fire Giant Strength"],
	["Dagger +1"],
	["Studded Leather +1"],
	["Fire Breath"],
	["Scroll of Protection - Weapons, Magical Missile"],
	["Battle Axe +3"],
	["Flail +2"],
	["Potion of Climbing"],
	["Potion of Poison"],
	["Scimitar +4"],
	["Dagger +1"],
	["Talisman of Pure Good"],
	["Leather Armor +2"],
	["Arrow +1","2-24"],
	["Scroll of Protection - Possession"],
	["Dagger +2","+3 vs. creatures larger than man-sized"],
	["Sword +2","Giant Slayer"],
	["Scroll of Protection","Petrification"],
	["Morning Star +1"],
	["Spear +1"],
	["Bolt +1","6-36"],
	["Trident of Fish Command"],
	["Elixir of Life"],
	["Oil of Acid Resistance"],
	["Plate Mail +1"],
	["Potion of Sweet Water"],
	["Rod of Passage"],
	["Sword +2","Dragon Slayer"],
	["Mace +1"],
	["Plate Armor, Field +2"],
	["Scroll of Protection"," Weapons, Magical Blunt"],
	["Oil of Impact"],
	["Wand of Magic Detection"],
	["Dagger +2","+3 vs. creatures larger than man-sized"],
	["Sword -2","Cursed"],
	["Oil of Impact"],
	["Potion of Invulnerability"],
	["Helm of Comprehending Languages and Reading Magic"],
	["Leather Armor +2"],
	["Phylactery of Faithfulness"],
	["Bolt +1","6-36"],
	["Shield +4"],
	["Staff of the Serpent"],
	["Chain Mail +1"],
	["Bolt +2","2-20"],
	["Trident of Fish Command"],
	["Robe of Eyes"],
	["Potion of Invulnerability"],
	["Trident of Warning"],
	["Wand of Enemy Detection"],
	["Battle Axe +3"],
	["Ring of Sustenance"],
	["Leather Armor +1"],
	["Ring of Shocking Grasp"],
	["Ring of Protection +1"],
	["Ring of Clumsinesss","Invisibility"],
	["Scroll of Protection","Petrification"],
	["Philter of Love"],
	["Elfin Chain Mail +1"],
	["Arrow +2","2-16"],
	["Sword +2"],
	["Chain Mail +2"],
	["Oil of Timelessness"],
	["Mace +2"],
	["Potion of ESP"],
	["Leather Armor +2"],
	["Crystal Hypnosis Ball"],
	["Sovereign Glue"],
	["Ring of Truth"],
	["Lance +1"],
	["Potion of Poison"],
	["","Small magical candle that burns without being consumed."],
	["","Spool that causes the thread wound on it to match the color of any fabric that it is touched to."],
	["","Small gold ring set with a magical stone that dimly glows any color the wearer desires."],
	["","Heart shaped locket that allows you to mentally send up to thirteen words once per day to the person whose name is engraved in the locket. They can immediately respond back with thirteen words."],
	["","Hat that keeps you magically dry in any rain."],
	["","Tent big enough for two people that folds, with its poles, into a 4 inch cube."],
	["","Pair of shoes or boots that never get dirty."],
	["","Egg sized stone that grows wet, cold, hot, or dry depending on the weather in 24 hours. If hung from a string the rock swings or hangs depending on the wind in 24 hours."],
	["","Vase that keeps any flowers placed in it from wilting."],
	["","Silver broach that can change into the shape of any flower the wearer is familiar with."],
	["","Pea sized crystal and a compass that always points toward the crystal."],
	["","Small copper feather that negates the first 20 feet of falling damage."],
	["","Fishing hook that wriggles like a worm negating the need for bait."],
	["","Magical stone hawk that can be set to attack any tiny or small beasts that approach within 300 feet."],
	["","Small box that opens on the top and bottom. Each side of the box opens into a separate extradimensional space the size of the box."],
	["","Stone mug carved with images of feasting dwarves. Any water put in the mug turns into dwarven ale. If you drink the ale you must make a BODY Check become drunk for the next 1d4 hours. While drunk you are poisoned and can speak Dwarven."],
	["","Rose from the Shrine of Roses that never wilts. Once per day the rose can cause a flowering plant to sprout flowers and bloom."],
	["","Sun Sphere from the Empire of the Sun. When activated the Sun Sphere looks like a miniature sun six inches across and provides light equal to a light spell."],
	["","Gemstone with a bloodshot and constantly roving beholder eye visible deep inside it. Once per day the owner can gain Advantage to a Check against a spell."],
	["","Flat iron rod with a button on one end. When the button is pressed the rod becomes magically fixed in place until the button is pressed again. The rod can hold up to 80 lbs of weight."],
	["","Horn that when blown can clearly be heard by everyone within 300 feet. After blowing the horn the users’ words are amplified for the next minute and can also be heard by everyone within 300 feet."],
	["","Ancient and unbreakable ring."],
	["","Necklace or circlet woven of meadow flowers that never wilt."],
	["","Key that opens any lock you locked."],
	["","Water skin that can hold a barrels worth of water (59 gallons)."],
	["","Bell that awakens anyone within 30 feet when rung."],
	["","Pair of glasses that gives you 10’ darkvision."],
	["","Sewing needle that will finish sewing any seam you started on its own."],
	["","Wood cutters axe or adze (treat as a hand axe) that deals double damage to wooden objects."],
	["","Small raven carved out of stone or wood. When activated the raven will count any humanoids it sees other than your allies. The raven can tell you how many humanoids it saw since it was activated."],
	["","Dragonfly carved out of jade that, when active, flies around you killing mosquitos and flies."],
	["","Tiny platinum figurine of Bahatmut that gives the bearer Advantage on diplomacy Checks with good dragons."],
	["","Preserved and shrunken eye set in a ring. While worn the bearer has Advantage on deception Checks to mimic animal sounds."],
	["","Pound of troll flesh that constantly regenerates providing enough meat every day for two humans. The flavor is disgusting."],
	["","Outfit of clothing that never gets dirty and magically mends any rips or tears."],
	["","Chamber pot that disintegrates any excrement put in it."],
	["","Comb made of bone that causes your hair to grow 1 inch for every minute you brush it. Your hair stops growing when it is as long as you are tall."],
	["","Pin with clear glass beads that keeps natural smoke at least 1 foot away from you."],
	["","Glowing rod that drives away dampness and moisture in a 10 foot radius."],
	["","Set of seven glowing magical gems that can be set swirling around you."],
	["","2\" tall animal spirit that is friendly and always remains within 5 feet of you."],
	["","Small blank book. As an action you can copy another book or other document into your book. The copy remains until you will it to be erased or copy another document."],
	["","Staff that can be turned into a tree or back into a staff."],
	["","Fish mask that lets you hold your breath twice as long as normal."],
	["","Petrified rat brain that lets you cast dominate monster once per long rest on a small or tiny rat or mouse."],
	["","Gold coin that you can summon back to your hand as long as it’s within 20 feet."],
	["","Small red gem that is warm to the touch. When the gem is placed on inanimate flammable material the material catches on fire in 1d4 rounds."],
	["","Holy symbol of Chauntea that you can activate once per day to weed, water, and care for a field of crops no larger than half an acre."],
	["","Holy symbol of Helm that you can activate once per day to gain Advantage to an initiative roll."],
	["","Holy symbol of Waukeen that gives you Advantage on Checks to run a business."],
	["","Holy symbol of Myrkul once per day you can use it to animate a tiny beast. The tiny skeleton or zombie remains under your control until it is destroyed or you animate a new undead. (AC 11, 1hp and unable to deal damage)"],
	["","Holy symbol of Amaunator that makes you immune to the exhaustion effects from hot weather."],
	["","Holy symbol of Moradin that makes you immune to the poisoning effects of alcohol."],
	["","Holy symbol of Eilistraee that allows you to sing beautifully."],
	["","Jar containing an aboleth mucus gland. If you breathe in the mucus you are able to breathe through your skin underwater for thirty minutes. The gland refills the jar with mucus in 24 hours."],
	["","Whistle that can only be heard by your allies."],
	["","Cup or plate that change color when they come in contact with poison."],
	["","Brass pitcher and a silver fly. As long as the fly is within 15 feet of the pitcher it whispers anything the pitcher hears."],
	["","Musical instrument that magically plays simple tunes and songs."],
	["","Small doll that mimics your movements."],
	["","Halter that when placed on a cow, donkey, mule, horse, or camel gives you Advantage on animal handling Checks for that beast."],
	["","Pack saddle that doubles the weight the beast wearing it can carry."],
	["","Obsidian ring that allows one individual you can see who can’t speak in Thieves’ Cant to understand you when you speak in Thieves’ Cant."],
	["","Mirror that can grow and shrink from hand sized to full length."],
	["","Ring that turns a willing wearer to stone until the ring is removed."],
	["","Nightcap that, when worn, gives you pleasant dreams."],
	["","Small fan with a humming bird painted on it that will hover near you and fan you."],
	["","Glass orb filled with smoke. If you concentrate on it an image of the person you are thinking about appears."],
	["","Stone orb that's half lit and half dark. The dark and light halves rotate around the orb once per day."],
	["","6\" long crystal coffin. When empty if touched to a dead body the body is shrunken and placed inside the coffin. The body can be released from the coffin by opening it. While in the coffin the body is protected from decay and can't become undead."],
	["","Iron pot or pan who’s handle never gets hot."],
	["","Feather of a Solar that is always immaculate. While holding it you can speak Celestial."],
	["","Horn from a Devil or Demon that allows you to speak Infernal or Abyssal respectively."],
	["","Spirit in the shape of a gear. The spirit can instantly count anything you can see or let you know when a specific amount of time has passed."],
	["","A dowsing rod that points to any water within 20 feet."],
	["","A wooden wand that lets you magically move unattended objects weight less than a pound that are within 15 feet."],
	["","Statue of a cricket that chirps softly in the dark. The cricket stops chirping if an invisible or incorporeal creature comes within 10 feet."],
	["","Collar that lets a dog or cat speak in common. It doesn’t change the animal’s intelligence."],
	["","Acorn that prevents you from being hit by natural lightning."],
	["","Finger bone from an executed man in a small wooden box. You have Advantage on death Checks while it’s in your possession."],
	["","Book of very short stories. Reading a story from the book (an action) acts like using a healer’s kit."],
	["Essence Extractor","Extract the consciousness of a pacified or willing being to be stored within. The consciousness can be injected into the still warm body of a dead being, giving them a new body to inhabit."],
	["Time Bomb","Time slows down sixty times in a 10m sphere around the blast. Lasts for a minute outside the sphere, or one second inside. One use."],
	["Helpful Bug","Metal replica of a beetle that can perform simple tasks."],
	["Plasmic Convertor","Turns a being's blood into a drop of liquid that grants single use of one special property the being has. 2-in-6 chance of converting an undesirable effect instead."],
	["Homunculus Gum","Whoever chews this gum bonds with the substance, which will begin to shape into a small gummy version of the chewer. It follows orders but has a bad attitude. Adding further gum will increase its size but decrease its loyalty. If somebody new chews up the homunculus, the bond transfers to them."],
	["Pheromone Pack","One dose each of Attraction, Rage, and Fear pheromones that work on any creature of animal intelligence."],
	["Beastmode Formula","Liquid tonic that grants the drinker the properties of a specific animal for one minute. Examples are Eyes of a Hawk, Nose of a Dog, Strength of a Bear etc. Three doses."],
	["Amnesia Fount","Stored at your house. Any head dunked into the water loses a specific memory as defined by the dunker. Anyone drinking the water absorbs all of the memories lost to the fount."],
	["Wish Spirit","Three measures of liquor that each grant a wish. The wish only lasts as long as the bracing kick of the liquor (d6 turns)."],
	["Duplicator","Coffin-sized box. Put one thing in, get two copies. Both copies are hugely inferior to the original."],
	["Mammoth Mask","Highly ornate with a prehensile trunk and tusks that can be used as a weapon (d6) at a push."],
	["Devourer","Football-sized bug that curls up in your backpack, but can be woken once per day to eat its own size in organic matter, no matter how inedible."],
	["Truth Leaf","Smoking this hallucinogenic herb reveals a ridiculous truth and a ridiculous lie. Three doses."],
	["Dehydrated Beasts","Three rubbery things resembling toy animals. If thrown into water, roll d6 to see what the thing expands into. 1: Mishydration (just a mass of twitching flesh), 2: Crush Beast (STR 18, 7hp, d12 Crush), 3: Brain Beast (WIL 18, 9hp, d8 Brain-Ray), 4: Wing Beast (12hp, d8 Beak), 5: Slime Beast (8hp, Armour 2, d6 Slime Spew), 6: Jaw Beast (STR 14, 10hp, d10 Jaws). When there's nothing left to kill, the creature collapses into inert powder."],
	["Hover Plate","Platter-sized tray that freezes in space if you whistle a specific tune. There's a second tune to release it. It supports up to one person's weight and can be forcibly released with a BODY Check."],
	["Genesis Molasses","Tin of deep green syrup that causes lush vegetation to grow within minutes, no matter where it is spread. If eaten, the victim loses 1 BODY and begins coughing up moss."],
	["Beserker Gland","When you take Ability Score Loss or suffer serious pain you fly into a rage. If your next attack is a melee attack, it is with Advantage. If it is ranged, it is with Disadvantage. Once the attack is out of your system you return to normal."],
	["Imprint Capsule","Any being that enters this booth is bombarded with smoke and emerges spluttering. They imprint upon the next being they see and dedicate their life to them until they next sleep."],
	["Terrormite","Big termite, pinned down in its box. Once released it burrows into the nearest living creature it can find, causing intense pain. Within a minute the victim develops a tough outer skin (Armour 18) and find they can spit acid (d6 ongoing). This lasts for an hour until the victim coughs out d6 Terrormite larva and returns to normal. If two terrormites enter the same host they fight inside them, causing d4 BODY loss."],
	["Chameleomole","Tiny mammal that can phase into any material without disturbing it. It can talk, but is extremely shy and will only answer a question with one word before phasing into hiding in their master's body."],
	["Earth-Angel","Tiny clay figurine that can be smashed to cause an earthquake. Those nearby are thrown to the ground and all structures take d12 damage."],
	["Wild Tongue","You can talk with any living thing, but what they tell you might not make sense."],
	["Spite Wisp","Glowing orb that materialises near to you whenever anybody gets badly hurt. If you will it, it will begin to attack the victim with sparks (d6), disappearing when they are subdued or killed."],
	["Threatening Probe","Has no function, but glows and vibrates in a way that suggests it could be used for distributing extreme pain."],
	["Caged Biter","A monkey-like creature (BODY 5, 5hp, d6 bite) in a cage. Once released it attacks its designated target and fights to the death, ignoring any further commands. If it wins, it eats some of its opponent before slinking back to its cage. It won't follow any other commands."],
	["Saucer Scar","You don't remember getting it. In the presence of artificial light it tingles, and you can will yourself to levitate slowly towards the light."],
	["Maiming Claw","A grappling hook that latches onto living tissue with an unbreakable grip. You know the trick for getting it to release."],
	["Trick Coin","Looks like a Silver Shilling but has three secret functions that you know how to use. First is a weak light. Second is a powerful magnet. Third is a d10 bomb (destroying the coin)."],
	["Universal Pin","A hair-pin that sticks into any surface, no matter the material. Causes no pain if stuck into flesh."],
	["Curse Doll","Anything significant that happens to the doll happens to you, beneficial or harmful."],
	["Snake-Cat","A cloth toy with a snake body and cat head. Once per day you can throw it on the ground and have it transform into a real snake (BODY 3, 4hp, d6 Bite) or cat (BODY 3, MIND 16, 4hp, d4 Claws) that loosely follows your commands. It returns to its cloth form after a few minutes."],
	["Second-Chance Skull","If you die, your body disintegrates to ash and immediately regenerates from this skull in perfect health."],
	["Jerk Sprite","A statuette of dried meat. Whatever eats this will act like an utter jerk for the next hour, even to their most loved ones."],
	["Powder Sack","Any powder stored in this small pouch becomes essentially unlimited. Turning the pouch inside out empties the current contents, with no unusual effect. Currently contains salt."],
	["Star-Beacon","Heavy tire-sized metal beacon (requires two people to carry) with a matching pin-badge. Pushing the badge teleports the wearer back to the beacon."],
	["Dire Barnacle","Three vicious little mollusks (1hp, AC 18) that explode in a 2m blast (d8) when killed."],
	["Ambrosia Seed","A bag of golden seed that any animal can't resist eating if thrown. If they're smart they'll realise you have the bag when the thrown seed runs out."],
	["Haunted Egg","A stone egg that can be used as a crude weapon (d6). The last thing killed by the egg will inhabit it as a ghostly voice, and will answer questions to the best of its knowledge. It doesn't have any more knowledge than it did in life, but anyone can understand its words."],
	["Tiny Shield Generator","Rat-sized collar that will creates a force-field (AC 16) around the wearer. Only works on subjects of chicken-size or smaller."],
	["Echojector","Hears up to ten seconds of sound and repeats it at vastly increased volume on command."],
	["Doom Siren","Tiny clockwork box lets out a booming drone when a being within 10ft dies."],
	["Stick Eye","Glass eye on a stick that the holder can see through."],
	["Champion's Mark","When you defeat a willing opponent unarmed (even as part of a group) you glow with health and gain the immediate effects of a Short Rest. If anyone defeats you unarmed the Mark transfers to them."],
	["Hell Spice","Extremely concentrated powdered hot spice. Enough to sabotage three meals."],
	["Bear Jelly","Pot of jelly that reeks of animal musk. Will scare off small creatures, but attract any large mammals."],
	["Orphan's Ruin","6oz of Milky drink. 1oz pacifies any unease, 2oz causes a deep sleep, 3oz eternal sleep."],
	["Steel Goggles","When switched on, objects that have a current owner glow faintly green, objects that have been taken from their rightful owner glow red. Objects that have no current claimant look normal."],
	["Parallel Shifter","Metal tin big enough to fit a pistol inside. If an object is placed inside and shaken, the object is replaced with a parallel version of itself from another reality. Roll d6. 1: Only ash remains. 2-5: The change is cosmetic but significant. 6: The new version is better than the old."],
	["Brain Jar","Jar of brine and wires that can sustain the brain of a freshly killed creature, allowing it to psychically project its thoughts. The brain must be fed blood or else it dies."],
	["Stinkincense","Pot of wax with a wick. When burned, sewage slowly drips over from the top of the jar. If left for an hour it will burn out, but produce enough sewage to fill a large room."],
	["Cosmic Ranker","Grey wand that, when waved between two objects, pulls to the object that it deems best by the standards requested. In case of a tie it flies from the wearer's hand."],
	["Rail-Lens","Any missile fired through this lens (breaking it) accelerates to impossible speeds, causing d10 damage and tearing through structures."],
	["Anti-matter Key","When placed in a keyhole, utterly annihilates the door. 1-in-6 chance of annihilating itself too."],
	["Nightmare Flower","Anyone sleeping in the same room as this flower suffers horrible nightmares. When they wake, they bring back the worst thing from their nightmare with them."],
	["Sanctuary Idol","Burning a candle in front of the idol causes smoke to billow out and reinforce all doors, open passageways, and windows into the room. Nothing can enter through these as long as the candle burns. Has no effect outdoors."],
	["Banker Pig","Clay pig with a coin slot. A copper coin causes an oinking sound. A silver piece causes it to transform into a normal pig for an hour. A gold coin causes it to transform into a vicious boar (7hp, d6 gore) for an hour. If it dies in pig form, it never transforms back."],
	["Evacuation Syrup","Removes any ill effects the drinker is suffering from, including anything short of death, but flushes the body clean in every sense. One dose."],
	["Savage Vine Berries","If eaten, rapidly growing vines erupt from the mouth (d6 HP loss) and grow into a sprawling vine filling a large room and clinging to whatever surface it can. 2 berries."],
	["Ghost Story","If you tell this story to somebody as they fall asleep, their ghostly skeleton leaves their body for the night, returning when they wake. The skeleton acts as the owner wishes and is completely immaterial."],
	["Companion Ball","Hollow ball that rolls behind you and never stops trying to follow you. Can pop open to store a head-sized object or smaller."],
	["Green Soil","Small pot of soil. Any plant that is planted into it will grow a whole season's worth of growth in one minute, but otherwise grows normally."],
	["Pyrophone","A klaxon-like horn that repels fire away from it."],
	["Stem-Stone","Pebble that transforms into whatever inorganic substance it last touched. Currently the leather of your pouch."],
	["Maggot Prince","Tiny maggot with a gold band marking. Flies and maggots will vacate the area to make room for it, and anything that eats bugs will be strongly drawn to try and eat it."],
	["Ovality Bomb","Explodes in a cloud of beige dust, forming a 2m high egg around the blast area. Nothing inside can break out, but the outside is easily broken. The egg keeps its contents alive in a happy stasis until released."],
	["Worldly Tortoise","Small tortoise (BODY 2, MIND 1, SPIRIT 6, 1hp, AC 1) that knows the way to anywhere you ask, but gets there very slowly."],
	["Fantastic Machine","Huge machine stored in an old factory. Has a slot where paper instructions can be inserted, with a coin slot for a 10s payment. After an hour of clinking it produces a rough approximation of the requested item, but anything fancy is poorly made."],
	["Unstoppable Rod","When thrown, nothing stops the movement of this rod, including gravity. Eventually flies off into space regardless of its trajectory."],
	["Slam Bomb","Causes all doors and windows in a large-room sized blast to slam open or shut, even if secured."],
	["Air-Sac","Membranous sac on your chest that you can inflate to 2m in diameter. Your lungs can draw on the air within, but remember the inflated sac floats."],
	["Gore Candle","Any injuries that happen in the presence of this candle's light are extra painful, messy, and harmful, doubling any HP loss caused."],
	["Skeletal Dove","Carefully assembled. Can be crushed to unleash a cloud of confused doves."],
	["Slaughter Brand","Three-pointed mark on your hand. When you kill a worthy opponent, one point turns darker. When all three points turn dark, your arm grows into an unnaturally strong, chitinous claw (d10 damage) for the next hour. When your arm returns, the brand resets."],
	["Noble Tumor","Visible growth absorbs the next harmful effect to enter your body, whether poison, parasite, curse, or otherwise, before dropping off."],
	["Blank Contract","Contract with blank parts. Can be modified into any sort of deal you wish. The first party to break the contract is blasted with a beam from above (d12, ignore armour) and the contract dissolves into shredded parchment."],
	["Utility Orb","Any tool that could plausibly exist in a mundane pocket-knife has a 50% chance of existing in this orb. Keep a track of what tools it does and doesn't have."],
	["Cocoon Wax","Anything covered in this wax is sealed off in a cocoon. After 24 hours it bursts free as a winged, hostile version of its previous self. One use."],
	["Plague Wart","Carefully extracted wart sealed in a jar. Anyone that touches it contracts a disgusting plague, losing 2 HP each hour. Any touch immediately spreads the plague. There is no cure that you know of."],
	["Ego-Mirror","Pocket mirror that functions as normal, but doesn't reflect anyone looking in."],
	["Fetch-Pearl","Silvery pearl that can attach to any item submerged in water. On a mental command from you, it floats to the surface, carrying whatever it is attached to. If attached to the ground, it just rips up a large chunk of it to fetch."],
	["Tiny Phantasm","Floating mass of swirling colours the size of a penny. It follows your every command and leaves a multicolour trail across any surface it touches. Cannot physically interact in any other way."],
	["Prosthetic Tail","Metal tail that straps to your body and functions as a third arm."],
	["Devil Salts","Awakens any creature from sleep or unconsciousness, but they flail and scream in terror for a few seconds first. They have no memory of this afterwards."],
	["Phase Tonic","A dose sends you out of sync with reality for ten seconds. You can act as normal, but when the tonic wears off, time snaps back to the point before you drank and all actions are undone. The dose is still consumed. 2 doses."],
	["Reconstruction Silk","Handkerchief that repairs any object it is draped over for an hour. The object must be small enough to be covered."],
	["Sabotage Disc","Disc of metal that can be slipped into even the most tightly cased machine, causing it to immediately malfunction in the most serious way possible."],
	["Preserved Soul","Tiny shriveled humanoid that can be thrown into a fire to release a flailing alien apparition (d8 eye-beams, immaterial, lashes out for 1d6 turns before vanishing in a flash of light)."],
	["Animation Oil","When rubbed onto an object, it springs to life for the next hour as your loyal servant. One dose."],
	["Pain Wire","Causes instant agony when touched by bare skin (you have gloves). 20m in length when uncoiled."],
	["Hunger Clamp","Small clamp that can be clipped onto loose skin, causing the victim to have a ceaseless hunger, which they'll do anything to sate. They suffer no ill effect from over-eating, but will not starve any faster than normal."],
	["Proxy Chain","When two or more beings are in contact with the chain, any harmful effects that affect one of them affect all instead."],
	["Tin Buddy","Can that springs out to a 2' tall automaton (2hp, Armour 18). He is loud, annoying, and doesn't do a good job of whatever you request. Has no real means of fighting."],
	["Gallon-Syringe","Tiny syringe that can draw up to a bath-sized amount of liquid."],
];